// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ✅ CONFIGURAÇÕES ATUALIZADAS COM BASE NO google-services.json
/// Project ID: quizz-5df8c
/// Project Number: 486337463820
/// App ID: 1:486337463820:android:9bf9c2111ff305e2e21029
/// API Key: AIzaSyBla1rLUQ_Ey1veod31KPpsWv69VjUPWlc
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ CONFIGURAÇÕES REAIS DO FIREBASE (baseadas no google-services.json)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBla1rLUQ_Ey1veod31KPpsWv69VjUPWlc',
    authDomain: 'quizz-5df8c.firebaseapp.com',
    databaseURL: 'https://quizz-5df8c-default-rtdb.firebaseio.com',
    projectId: 'quizz-5df8c',
    storageBucket: 'quizz-5df8c.firebasestorage.app',
    messagingSenderId: '486337463820',
    appId: '1:486337463820:web:9bf9c2111ff305e2e21029',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBla1rLUQ_Ey1veod31KPpsWv69VjUPWlc',
    authDomain: 'quizz-5df8c.firebaseapp.com',
    databaseURL: 'https://quizz-5df8c-default-rtdb.firebaseio.com',
    projectId: 'quizz-5df8c',
    storageBucket: 'quizz-5df8c.firebasestorage.app',
    messagingSenderId: '486337463820',
    appId: '1:486337463820:android:9bf9c2111ff305e2e21029',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBla1rLUQ_Ey1veod31KPpsWv69VjUPWlc',
    authDomain: 'quizz-5df8c.firebaseapp.com',
    databaseURL: 'https://quizz-5df8c-default-rtdb.firebaseio.com',
    projectId: 'quizz-5df8c',
    storageBucket: 'quizz-5df8c.firebasestorage.app',
    messagingSenderId: '486337463820',
    appId: '1:486337463820:ios:9bf9c2111ff305e2e21029',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBla1rLUQ_Ey1veod31KPpsWv69VjUPWlc',
    authDomain: 'quizz-5df8c.firebaseapp.com',
    databaseURL: 'https://quizz-5df8c-default-rtdb.firebaseio.com',
    projectId: 'quizz-5df8c',
    storageBucket: 'quizz-5df8c.firebasestorage.app',
    messagingSenderId: '486337463820',
    appId: '1:486337463820:macos:9bf9c2111ff305e2e21029',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBla1rLUQ_Ey1veod31KPpsWv69VjUPWlc',
    authDomain: 'quizz-5df8c.firebaseapp.com',
    databaseURL: 'https://quizz-5df8c-default-rtdb.firebaseio.com',
    projectId: 'quizz-5df8c',
    storageBucket: 'quizz-5df8c.firebasestorage.app',
    messagingSenderId: '486337463820',
    appId: '1:486337463820:windows:9bf9c2111ff305e2e21029',
  );
} 